apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
  namespace: app-dev
spec:
  selector:
    app: app-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
