apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: ClusterIP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.containerPort | default 80 }}
