{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "app.fullname" .)) }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.secrets.dbUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
{{- end }}
