apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.secrets.dbUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
