global:
  env: dev

backend:
  replicaCount: 1

  image:
    repository: 985539792593.dkr.ecr.us-east-1.amazonaws.com/app-backend
    tag: latest
    pullPolicy: IfNotPresent

  containerPort: 8080

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

frontend:
  replicaCount: 1

  image:
    repository: 985539792593.dkr.ecr.us-east-1.amazonaws.com/app-frontend
    tag: latest
    pullPolicy: IfNotPresent

  containerPort: 80

ingress:
  enabled: true
  host: ""
  className: alb

secrets:
  create: false
  name: app-app-secrets
