global:
  env: prod

backend:
  replicaCount: 2
  containerPort: 8080
  image:
    repository: 985539792593.dkr.ecr.us-east-1.amazonaws.com/app-backend
    tag: "latest"
    pullPolicy: Always

frontend:
  replicaCount: 2
  containerPort: 80
  image:
    repository: 985539792593.dkr.ecr.us-east-1.amazonaws.com/app-frontend
    tag: "latest"
    pullPolicy: Always

ingress:
  enabled: true
  host: ""

secrets:
  create: false
  name: "app-app-secrets"
