postgres:
  replicas: 1
  image:
    repository: postgres
    tag: "17"

postgresConfig:
  db: myappdb
  user: appuser

  existingSecret: postgres-credentials
  passwordKey: POSTGRES_PASSWORD

persistence:
  enabled: true
  size: 5Gi
  storageClass: gp3
