apiVersion: v1
kind: Namespace
metadata:
  name: ci
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
