apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::985539792593:role/eks-nodegroup-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::985539792593:role/ansible-eks-role
      username: ansible
      groups:
        - system:masters

    - rolearn: arn:aws:iam::985539792593:role/jenkins-irsa-role
      username: system:serviceaccount:ci:jenkins
      groups:
        - system:masters

