apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerd-insecure-registry
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: containerd-insecure-registry
  template:
    metadata:
      labels:
        name: containerd-insecure-registry
    spec:
      hostPID: true
      containers:
        - name: configure-containerd
          image: busybox
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              mkdir -p /etc/containerd
              cat <<EOF > /etc/containerd/config.toml
              version = 2

              [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors."a8bcd90ff89904a28acd94cd112c6650-8a32720f9a3344d2.elb.us-east-1.amazonaws.com:8082"]
                  endpoint = ["http://a8bcd90ff89904a28acd94cd112c6650-8a32720f9a3344d2.elb.us-east-1.amazonaws.com:8082"]
              EOF

              systemctl restart containerd
              sleep 3600
          volumeMounts:
            - name: etc-containerd
              mountPath: /etc/containerd
      volumes:
        - name: etc-containerd
          hostPath:
            path: /etc/containerd
