apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-docker-ingress
  namespace: eks-build
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nexus.local
      secretName: nexus-tls
  rules:
    - host: nexus.local
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: nexus-docker-service
                port:
                  number: 8082

